# Generated by Django 4.2 on 2023-04-22 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_product_sku'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reparationproduct',
            unique_together={('vehicle', 'date_repaired')},
        ),
        migrations.CreateModel(
            name='ReparationProductItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
                ('reparation_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.reparationproduct')),
            ],
        ),
        migrations.RemoveField(
            model_name='reparationproduct',
            name='product',
        ),
        migrations.RemoveField(
            model_name='reparationproduct',
            name='quantity',
        ),
        migrations.AddField(
            model_name='reparationproduct',
            name='products',
            field=models.ManyToManyField(through='inventory.ReparationProductItem', to='inventory.product'),
        ),
    ]
